In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [23]:
# Load dataset file
dataset = pd.read_csv("iris.csv")

In [24]:
# Get some basic information about the loaded dataset
print(dataset.shape)
print(dataset.head(5))
print(dataset.describe())


(150, 6)
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.3000

In [25]:
# Check if the dataset instances are properly distributed
print(dataset.groupby('Species').size())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


In [154]:
# Create input (X) and output_labels (Y) vectors
feature_columns = ['PetalWidthCm','SepalLengthCm','SepalWidthCm']
#feature_columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm','PetalWidthCm']

X = dataset[feature_columns].values
y = dataset['Species'].values


In [155]:
# Apply numerical encoding to convert alphabetical names
le = LabelEncoder()
y = le.fit_transform(y)

In [156]:
# Divide the dataset in testing and training vectors for cross-validation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [157]:
# Instantiate learning model (k = 3)
classifier = KNeighborsClassifier(n_neighbors=3)

In [158]:
# Fitting the model
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [159]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [160]:
from sklearn.neighbors import KNeighborsClassifier
#from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
#from sklearn.tree import DecisionTreeClassifier
#from sklearn.svm import SVC
#from sklearn.linear_model import LogisticRegression





classifier = KNeighborsClassifier(n_neighbors=5)
#classifier = LinearDiscriminantAnalysis()
#classifier = DecisionTreeClassifier()
#classifier = SVC(gamma = 'auto')
#classifier = LogisticRegression()



# Fitting the model
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [161]:
#print(classifier.coef_)

In [162]:
# Create and view the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[13  0  0]
 [ 0 14  2]
 [ 0  1  8]]


In [163]:
# View the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')



Accuracy of our model is equal 92.11 %.


In [153]:
#On 0.3 with n=5

#SepalLength=57.78%
#SepalWidth=64.44%
#PetalLength=95.56%
#PetalWidth=97.78%
#SL+PL=97.78%
#SL+PW=95.56%
#SW+PL=93.33%
#SW+PW=95.56%
#SL+SW=73.33%
#PL+PW=97.78%
#SL+PL+PW=97.78%
#SW+PL+PW=97.78%
#PL+SL+SW=97.78%
#PW+SL+SW=93.33%


In [19]:
#Change only one paramater i.e test

#On 0.2 with n=5

#SepalLength=56.67%
#SepalWidth=56.67%
#PetalLength=96.67%
#PetalWidth=96.67%
#SL+PL=100%
#SL+PW=96.67%
#SW+PL=96.67%
#SW+PW=96.67%
#SL+SW=66.67%
#PL+PW=100%
#SL+PL+PW=100%
#SW+PL+PW=100%%
#PL+SL+SW=93.33%
#PW+SL+SW=69.67%



In [20]:
#On 0.25 N=3

#SepalLength=60.53%
#SepalWidth=57.89%
#PetalLength=89.47%
#PetalWidth=97.37%
#SL+PL=97.37%
#SL+PW=97.37%
#SW+PL=94.74%
#SW+PW=94.74%
#SL+SW=76.32%
#PL+PW=97.37%
#SL+PL+PW=97.37%
#SW+PL+PW=97.37%
#PL+SL+SW=97.37%
#PW+SL+SW=92.11%%
